- name: Create or update Kubernetes secret with retry
      run: |
        echo "Creating or updating Kubernetes secret..."
        max_retries=3
        retry_count=0
        
        while [ $retry_count -lt $max_retries ]; do
          # Use kubectl create with --dry-run=client and pipe to kubectl apply
          if kubectl create secret generic db-secret \
              --from-literal=password=${{ secrets.RDS_PASSWORD }} \
              --dry-run=client -o yaml | kubectl apply -f - --request-timeout=30s; then
            echo "✅ Kubernetes secret created/updated successfully"
            break
          else
            retry_count=$((retry_count + 1))
            echo "❌ Failed to create/update secret (attempt $retry_count/$max_retries)"
            if [ $retry_count -lt $max_retries ]; then
              echo "Retrying in 15 seconds..."
              sleep 15
            fi
          fi
        done
        
        if [ $retry_count -eq $max_retries ]; then
          echo "❌ Failed to create/update Kubernetes secret after $max_retries attempts"
          exit 1
        fi
