name: Deploy Node.js App to EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nodejs-app

jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      ecr_repo_url: ${{ steps.terraform.outputs.ecr_repo_url }}
      rds_endpoint: ${{ steps.terraform.outputs.rds_endpoint }}
      cluster_name: ${{ steps.terraform.outputs.cluster_name }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: infra

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: infra
      env:
        TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
        TF_VAR_cluster_name: ${{ env.CLUSTER_NAME }}
        TF_VAR_region: ${{ env.AWS_REGION }}

    - name: Get Terraform outputs
      id: terraform
      run: |
        # Function to get clean terraform output
        get_terraform_output() {
          local output_name=$1
          terraform output -raw "$output_name" 2>/dev/null | tr -d '\r\n\t' | sed 's/[^[:print:]]//g'
        }
        
        # Get outputs
        ECR_REPO_URL=$(get_terraform_output ecr_repository_url)
        RDS_ENDPOINT=$(get_terraform_output rds_endpoint)
        CLUSTER_NAME=$(get_terraform_output cluster_name)
        
        # Set job outputs
        echo "ecr_repo_url=$ECR_REPO_URL" >> $GITHUB_OUTPUT
        echo "rds_endpoint=$RDS_ENDPOINT" >> $GITHUB_OUTPUT
        echo "cluster_name=$CLUSTER_NAME" >> $GITHUB_OUTPUT
        
        # Debug output
        echo "✅ ECR Repository URL: $ECR_REPO_URL"
        echo "✅ RDS Endpoint: $RDS_ENDPOINT"
        echo "✅ Cluster Name: $CLUSTER_NAME"
      working-directory: infra

  deploy-application:
    runs-on: ubuntu-latest
    needs: provision-infrastructure
    env:
      ECR_REPO_URL: ${{ needs.provision-infrastructure.outputs.ecr_repo_url }}
      RDS_ENDPOINT: ${{ needs.provision-infrastructure.outputs.rds_endpoint }}
      CLUSTER_NAME_OUTPUT: ${{ needs.provision-infrastructure.outputs.cluster_name }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t $ECR_REPO_URL:$GITHUB_SHA -f app/Dockerfile ./app
        docker tag $ECR_REPO_URL:$GITHUB_SHA $ECR_REPO_URL:latest
        
        echo "Pushing Docker image..."
        docker push $ECR_REPO_URL:$GITHUB_SHA
        docker push $ECR_REPO_URL:latest
        
        echo "✅ Docker image pushed successfully"

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

    - name: Create Kubernetes secret
      run: |
        kubectl create secret generic db-secret \
          --from-literal=password=${{ secrets.RDS_PASSWORD }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy Node.js application
      run: |
        # Replace placeholders in manifest
        sed -i "s|{{IMAGE_URI}}|$ECR_REPO_URL:$GITHUB_SHA|g" k8s/deployment.yaml
        sed -i "s|{{RDS_ENDPOINT}}|$RDS_ENDPOINT|g" k8s/deployment.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        
        # Wait for rollout
        kubectl rollout status deployment/nodejs-app --timeout=180s

    - name: Deploy monitoring stack
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --create-namespace \
          --set grafana.adminPassword=${{ secrets.GRAFANA_ADMIN_PASSWORD }} \
          --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
          --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false
